### PR TITLE
Makes lfs/_init.lua compatible with Lua 5.3

### LINKED ISSUE #3156: LFS under Lua 5.3
I'm sorry I don't have time to study the issue myself now. So maybe I am reporting something while the issue is on the other side of the keyboard. I guess this has some easy solution.

### Expected behavior
LFS example working under Lua 5.3

### Actual behavior
```Lua
node.flashindex("_init")()
Lua error: _init.lua:55: attempt to call a nil value (global 'getfenv')
stack traceback:
	_init.lua:55: in main chunk
	stdin:1: in main chunk
	[C]: in ?
	[C]: in ?
```

### Test code
Standard [LFS example](/nodemcu/nodemcu-firmware/tree/master/lua_examples/lfs) loaded in LFS.
```Lua
node.flashindex("_init")()
```
### NodeMCU startup banner
```
NodeMCU 3.0.0.0 built with Docker provided by frightanic.com
	branch: watertank
	commit: 78ab92f24021bb843e611f4daac0124649304f7f
	release: 2.0.0-master_20170202 +523
	release DTS: 202006112149
	SSL: false
	build type: float
	LFS: 0x10000 bytes total capacity
	modules: enduser_setup,file,gpio,http,net,node,rtcmem,rtctime,sjson,sntp,sun,tmr,uart,wifi
 build 2020-06-11 22:06 powered by Lua 5.3.5 on SDK 3.0.1-dev(fce080e)
```

### Hardware
ESP8266 ESP-12E

### PR DESCRIPTION
**Pull request by vsky279**
Fixes #3156.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

This commit makes [lua_examples/lfs/_init.lua](/nodemcu/nodemcu-firmware/blob/master/lua_examples/lfs/_init.lua) compatible with Lua 5.3.

### CODE REVIEW

File: lua_examples/lfs/_init.lua [hunk 1]
```diff
@@ -8,10 +8,10 @@
   module related initialisaion in this. This example uses standard Lua features to
   simplify the LFS API.
 
-  The first section adds a 'LFS' table to _G and uses the __index metamethod to
-  resolve functions in the LFS, so you can execute the main function of module
-  'fred' by executing LFS.fred(params), etc. It also implements some standard
-  readonly properties:
+  For Lua 5.1, the first section adds a 'LFS' table to _G and uses the __index 
+  metamethod to resolve functions in the LFS, so you can execute the main 
+  function of module 'fred' by executing LFS.fred(params), etc.
```
Comment (nwf) [inline lua_examples/lfs/_init.lua:13]: +"For Lua 5.3, equivalent functionality is provided natively by the firmware" ?

File: lua_examples/lfs/_init.lua [hunk 2]
```diff
@@ -24,36 +24,45 @@
...
+      end,
   }
 
-local G=getfenv()
-G.LFS = setmetatable(lfs_t,lfs_t)
+  G.LFS = setmetatable(lfs_t,lfs_t) 
+  --[[-------------------------------------------------------------------------------
+    You can add any other initialisation here, for example a couple of the globals
+    are never used, so setting them to nil saves a couple of global entries
+  ---------------------------------------------------------------------------------]]
```
Comment (nwf) [inline lua_examples/lfs/_init.lua:61]: Split this comment in twain; this, being gated by the `_VERSION` check, is not where we want to encourage users to extend `_init.lua`, but these next lines still need some commentary.

File: lua_examples/lfs/_init.lua [hunk 3]
```diff
@@ -96,6 +96,4 @@ G.dofile = function(n)
   local mod, ext = n:match("(.*)%.(l[uc]a?)");
   local fn, ba   = index(mod)
```
Comment (nwf) [inline lua_examples/lfs/_init.lua:97]: Here (and above), `index` will not refer to `node.flashindex()` because that `local` definition is now scoped within the `_VERSION` check.  I suspect you can rewrite these to use the `LFS` table that's now guaranteed to exist (**utterly untested, almost surely wrong**)...

```
local mod, ext = n:match("(.*)%.(l[uc]a?)");
if ext ~= 'lc' and ext ~= 'lua' then return df(n) else return LFS[mod] or df(n) end
```

Comment (vsky279) [reply lua_examples/lfs/_init.lua:97]: :rage: that was not a good optimization...

File: lua_examples/lfs/_init.lua (hunk 1 above)
Comment (vsky279) [reply lua_examples/lfs/_init.lua:13]: "For Lua 5.3 LFS table is populated by the LFS implementation in C so this part of the code is skipped." ?

File: lua_examples/lfs/_init.lua (hunk 2 above)
Comment (vsky279) [reply lua_examples/lfs/_init.lua:61]: Do you mean to have this section also in the `else` part of the `_VERSION` check?
There's no need to nil `G.module` and `package.seeall` under Lua 5.3.
Or do we just modify the comment that it applies to Lua 5.1 solely?

**Comment by vsky279** [comment]
How do we solve the
```
lua_examples/lfs/_init.lua:31:9: accessing undefined variable _ENV
lua_examples/lfs/_init.lua:79:10: accessing undefined variable LFS
```
luacheck error?
Will there be 2 `luacheck_config.lua`? One for Lua 5.1 and Lua 5.3?

File: lua_examples/lfs/_init.lua (hunk 2 above)
Comment (nwf) [reply lua_examples/lfs/_init.lua:61]: I just mean that the encouragement "You can add any other initialisation here" is now out of place.

File: lua_examples/lfs/_init.lua [hunk 4]
```diff
@@ -96,6 +96,4 @@ G.dofile = function(n)
...
   if ba or (ext ~= 'lc' and ext ~= 'lua') then return df(n) else return fn() end
-end
-
-
+end
```
Comment (marcelstoer) [inline lua_examples/lfs/_init.lua:99]: Missing a newline here.

**Comment by nwf** [comment]
This will need further revision in light of #3176.  Blocked until that lands, I think.

**Comment by vsky279** [comment]
Merging now would mean to have the example compatible with Lua 5.3. Another rework should follow #3176 imho.

**Comment by nwf** [comment]
That seems like an OK plan to me. @TerryE?

**Comment by TerryE** [comment]
> That seems like an OK plan to me. @TerryE?

There are +/-'s here.  Anyone that needs `_init.lua` support for 5.3 can use this code, but I am trying to get the PR which addresses #3175, #3176 and #3180 out in the next few days, and merging this now means that I will have to do a rebase before I can create this PR which is going to add to this timeline. 

BTW, it's my wife's birthday today, so I don;t want to be locked away in my study today. :smile:

File: lua_examples/lfs/_init.lua [hunk 5]
```diff
@@ -24,36 +24,40 @@
...
-        return nil
-      end
-    end,
-
-  __newindex = function(_, name, value) -- luacheck: no unused
-      error("LFS is readonly. Invalid write to LFS." .. name, 2)
-    end,
-
+local G=_ENV or getfenv()
+if _VERSION == 'Lua 5.1' then
```
Comment (TerryE) [inline lua_examples/lfs/_init.lua:33]: We need to set `_G.LFS` to `node.LFS` on the `else` branch,  otherwise `LFS` will not resolve for the require code @ 74.  Though IMO, it would be better to hoist local `lfs_t` which is then set by the `if _VERSION` code as per 5.1 or 5.3 (the 5.1 path includes the `setmetatable()`) and move the `G.LFS = lfs_t` to the common path.  Then L74 can refer to the close upval `lfs_t`.

Comment (vsky279) [reply lua_examples/lfs/_init.lua:34]: This was before `node.LFS` was implemented.
I like the idea to use upvalue in `package.loaders[3]` handler.

File: tools/luacheck_config.lua [hunk 6]
```diff
@@ -430,6 +430,16 @@ stds.nodemcu_libs = {
...
           }
+        },
+        LFS = {
+          read_only = true, 
+          fields = {
+            config = empty,
+            get = empty,
+            list = empty,
+            reload = empty,
+            tiem = empty
```
Comment (nwf) [inline tools/luacheck_config.lua:441]: `time`?

File: tools/luacheck_config.lua [hunk 7]
```diff
@@ -430,6 +430,16 @@ stds.nodemcu_libs = {
             MEDIUM_PRIORITY = empty,
             HIGH_PRIORITY = empty
           }
+        },
+        LFS = {
+          read_only = true, 
+          fields = {
```
Comment (nwf) [inline tools/luacheck_config.lua:436]: Not really a question for this PR, but since you're in the neighborhood: should we suggest to advanced developers how to add entries here?  People using their own LFS might want their code to still be `luacheck`-clean?

**Comment by nwf** [comment]
Sure, what's the worst that happens. ;)

File: tools/luacheck_config.lua (hunk 7 above)
Comment (galjonsfigur) [reply tools/luacheck_config.lua:436]: @nwf I think it would be a good idea to make some kind of documentation on how to use `luacheck` on NodeMCU code. I've written `luacheck_config_helper.lua` script when I was adding `luacheck` support but I haven't documented it anywhere besides some comments in the script itself. Should this be added to GitHub Wiki,  Extension Developer FAQ or somewhere else?

Comment (TerryE) [reply tools/luacheck_config.lua:436]: > I think it would be a good idea to make some kind of documentation on how to use `luacheck` on NodeMCU code.

I am more of the view: what's wrong with RTFM?  If anyone wants to read up on how to use luacehck then it comes with a lot of good documentation.  May a reference to it in our FAQs.
