### PR TITLE
httpserver: fix memory leak

### LINKED ISSUE #3364: httpserver: memory leak due to not dropping all references to fifosocket
### Expected behavior

Multiple consecutive HTTP GET requests to a httpserver running on a NodeMCU do not cause the platform to OOM and crash.

### Actual behavior

Multiple consecutive HTTP GET requests to a httpserver running on a NodeMCU cause crash.

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```
station_cfg={}
station_cfg.ssid="..."
station_cfg.pwd="..."
station_cfg.auto=true
station_cfg.save=false

wifi.setmode(wifi.STATION)
wifi.sta.config(station_cfg)
print(wifi.sta.getip())

require("httpserver").createServer(80, function(req, res)
    res:finish("Error", 500)
end)
```
After uploading this code issue 100 GET requests (one after another) to the so created server.

### NodeMCU startup banner
```
NodeMCU 3.0.0.0 
	branch: release
	commit: 64bbf006898109b936fcc09478cbae9d099885a8
	release: 3.0-master_20200910
	release DTS: 202009090323
	SSL: false
	build type: float
	LFS: 0x0 bytes total capacity
	modules: adc,bit,dht,file,gpio,i2c,mqtt,net,node,ow,spi,tmr,uart,wifi
 build 2020-10-22 19:48 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
```

### Hardware
ESP8266 on a LOL1n board. I don't believe this is hardware-specific in any way.

### PR DESCRIPTION
**Pull request by jpotoniec**
Fixes #3364

- [x] This PR is for the `dev` branch rather than for the `release` branch.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [ ] The code changes are reflected in the documentation at `docs/*`.

### CODE REVIEW

File: lua_modules/http/httpserver.lua [hunk 1]
```diff
@@ -86,19 +86,22 @@ do
...
+        connection:on("disconnection", nil)
+        connection:on("sent", nil)
+        collectgarbage("collect")
+      end
+
       local cfini = function()
-        conn:on("receive", nil)
-        conn:on("disconnection", nil)
         csend(function()
           conn:on("sent", nil)
```
Comment (galjonsfigur) [inline lua_modules/http/httpserver.lua:98]: This line could be removed as this will be called in `ondisconnect` anyway

**Review by galjonsfigur — APPROVED** [review]
I tested it with `curl -i -X GET http://esp-address` and replicated the issue. After unregistering those callbacks the leak is gone. Thanks for the report and the PR! Other than that one redundant line, it can be merged.
