### PR TITLE
MQTT memory / connection issues fix

### LINKED ISSUE #1349: MQTT Client never freed (memory leak)
### Expected behavior
After `failure` callback or `:close()` method and nullified pointer, all memory that used by client is freed (heap before creation == heap after destroy)

### Actual behavior
Memory leak

### Test code
mqtt.lua
```lua
local client = mqtt.Client( 'Test client', 120, nil, nil, 1 )
client:on('connect', function(client)
    print('CONN')
    client:subscribe("esp/mqtt/test", 0)
    client:publish("esp/mqtt/test", "test", 0, 0)
end)
client:on('message', function(client, topic, message)
    print("RECV", topic, message)
    client:close()
end)
return client
```
mqtt-unsecure.lua
```lua
dofile('mqtt.lua'):connect( "85.119.83.194", 1883,
    0, 0, nil,
    function(client, err)
        print("CONN FAIL", err)
    end
)
```
mqtt-secure.lua
```lua
dofile('mqtt.lua'):connect( "85.119.83.194", 8883,
    1, 0, nil,
    function(client, err)
        print("CONN FAIL", err)
    end
)
```

example output (disconnected):
```
> =node.heap()
43640
> dofile("mqtt-unsecure.lua")
CONN FAIL	-5
> = collectgarbage(), node.heap()
0	42696
> dofile("mqtt-secure.lua")
CONN FAIL	-5
> = collectgarbage(), node.heap()
0	41504
... after some time ...
> = collectgarbage(), node.heap()
0	41704
```
example output (wifi connection):
```
= collectgarbage(), node.heap()
0	43520
> dofile("mqtt-secure.lua")
CONN
RECV	esp/mqtt/test	test
> = collectgarbage(), node.heap()
0	43480
> dofile("mqtt-unsecure.lua")
CONN
RECV	esp/mqtt/test	test
> = collectgarbage(), node.heap()
0	43264
... after some time ...
> = collectgarbage(), node.heap()
0	43312
```
### NodeMCU version
Current master (1.5.1)

### Hardware
NodeMCU DevKit 1.0

### PR DESCRIPTION
**Pull request by djphoenix**
Fixes #1349, #1406.

### CODE REVIEW

**Comment by marcelstoer** [comment]
We already established that it does fix the bugs indeed. So, all we need is someone to give this a formal code review.

File: app/modules/mqtt.c [hunk 1]
```diff
@@ -873,8 +885,7 @@ static sint8 socket_connect(struct espconn *pesp_conn)
 #ifdef CLIENT_SSL_ENABLE
   if(mud->secure)
   {
-      espconn_secure_set_size(ESPCONN_CLIENT, 5120); /* set SSL buffer size */
```
Comment (devsaurus) [inline app/modules/mqtt.c]: You remove `espconn_secure_set_size()` here and perform it once during module initialization. I suspect that this  creates interdependencies to other modules that change the setting in the meantime. You can't be sure about the current value when execution reaches this point unless there's a global convention.

File: app/modules/mqtt.c [hunk 2]
```diff
@@ -971,22 +982,21 @@ static int mqtt_socket_connect( lua_State* L )
...
-    if(mud->pesp_conn->proto.tcp)
-      c_free(mud->pesp_conn->proto.tcp);
-    mud->pesp_conn->proto.tcp = NULL;
-    c_free(mud->pesp_conn);
-    mud->pesp_conn = NULL;
+  struct espconn *pesp_conn = mud->pesp_conn;
+  if(!pesp_conn) {
+    pesp_conn = mud->pesp_conn = (struct espconn *)c_zalloc(sizeof(struct espconn));
+  } else {
+    espconn_delete(pesp_conn);
```
Comment (devsaurus) [inline app/modules/mqtt.c]: Is the state of `pesp_conn` equivalent after the two `if` branches? Can it be re-used below if it's deleted here? The API guide is not clear in this respect IMO.

File: app/modules/mqtt.c [hunk 3]
```diff
@@ -971,22 +982,21 @@ static int mqtt_socket_connect( lua_State* L )
...
-  struct espconn *pesp_conn = NULL;
-  pesp_conn = mud->pesp_conn = (struct espconn *)c_zalloc(sizeof(struct espconn));
   if(!pesp_conn)
     return luaL_error(L, "not enough memory");
-
-  pesp_conn->proto.udp = NULL;
-  pesp_conn->proto.tcp = (esp_tcp *)c_zalloc(sizeof(esp_tcp));
+  if(pesp_conn->proto.udp) {
+    pesp_conn->proto.udp = NULL;
+    c_free(pesp_conn->proto.udp);
```
Comment (devsaurus) [inline app/modules/mqtt.c]: `c_free(NULL)` is a no-op. Should lines 995 and 996 be swapped?

File: app/modules/mqtt.c [hunk 4]
```diff
@@ -1609,6 +1622,7 @@ static const LUA_REG_TYPE mqtt_map[] = {
 int luaopen_mqtt( lua_State *L )
 {
   luaL_rometatable(L, "mqtt.socket", (void *)mqtt_socket_map);  // create metatable for mqtt.socket
+  espconn_secure_set_size(ESPCONN_CLIENT, 4096);
```
Comment (devsaurus) [inline app/modules/mqtt.c]: Needs `#ifdef CLIENT_SSL_ENABLE`?

File: app/modules/mqtt.c (hunk 2 above)
Comment (djphoenix) [inline app/modules/mqtt.c]: Don't see any issues here. Now it works for me, both for secure and unsecure variants.

File: app/modules/mqtt.c (hunk 4 above)
Comment (djphoenix) [inline app/modules/mqtt.c]: Espconn have not depends to our configuration. However, it's a good point. ACK

File: app/modules/mqtt.c (hunk 3 above)
Comment (djphoenix) [inline app/modules/mqtt.c]: Oh... Will research. It works, without leaks, but...

File: app/modules/mqtt.c (hunk 1 above)
Comment (djphoenix) [inline app/modules/mqtt.c]: In case of set size for each connection there was some memory leaks... Maybe it fixed, will try to move back and test.

Comment (devsaurus) [inline app/modules/mqtt.c]: > In case of set size for each connection there was some memory leaks

Interesting point, would be important to know for the other modules as well.

File: app/modules/mqtt.c (hunk 2 above)
Comment (devsaurus) [inline app/modules/mqtt.c]: Ok.

**Comment by NicolSpies** [comment]
@djphoenix Hi Jury, I have been monitoring a unit the last 2 weeks **running on the existing dev without your fixes** and observe the following that might be of interest to the MQTT connection state.

1. Over a period of time the MQTT connection appears to be fine as I publish once a minute.
2. As soon as a message is received the connection drops.
3. I restart the ESP and a fresh MQTT connection is established.
4. Now messages can be received without any problems

If this phenomena corresponds to what you have already fixed, please ignore. As soon as the fix has been merged with dev I will load on the "field" ESP unit and continue the testing.

Regards

**Comment by djphoenix** [comment]
Oh... Don't seen smth like this anyway. But situation should be more stable after merge.

**Comment by djphoenix** [comment]
Fixed all commented places.

File: app/modules/mqtt.c (hunk 3 above)
Comment (djphoenix) [inline app/modules/mqtt.c]: So yes, `proto` field is `union`. In case of MQTT, we will never touch UDP part. Removed entire block.

**Comment by devsaurus** [comment]
Good to go, thanks Yury!

**Comment by NicolSpies** [comment]
Thanks Yury, much much appreciated
