### PR TITLE
Fixes `net.ifinfo` failure

### LINKED ISSUE #3249: net.ifinfo fails with "Lua error: attempt to index a number value" or MCU reboot
### Expected behavior
`net.ifinfo()` should return nil or a table.

### Actual behavior
```text
@0.00s  > =net.ifinfo(0)
@0.05s  Lua error: attempt to index a number value
@0.05s  stack traceback:
@0.05s  	[C]: in function 'ifinfo'
@0.05s  	stdin:1: in main chunk
@0.05s  	[C]: ?
@0.05s  	[C]: ?
@1.94s  > =net.ifinfo()
@9.29s   ets Jan  8 2013,rst cause:4, boot mode:(3,6)
@9.29s  wdt reset
@9.29s  load 0x40100000, len 30132, room 16 
@9.31s  tail 4
@9.31s  chksum 0x4b
@9.31s  load 0x3ffe8000, len 2772, room 4 
@9.32s  tail 0
@9.32s  chksum 0x2b
@9.32s  load 0x3ffe8ad4, len 8, room 8 
@9.32s  tail 0
@9.32s  chksum 0x4f
@9.32s  csum 0x4f
… noise …
@9.49s  NodeMCU 3.0.0.0 built with Docker provided by frightanic.com
@9.49s  	branch: master
@9.50s  	commit: 8d091c476edf6ae2977a5f2a74bf5824d07d6183
@9.50s  	release: 3.0-master_20200610
@9.50s  	release DTS: 202006092026
@9.50s  	SSL: false
@9.50s  	build type: float
@9.51s  	LFS: 0x00010000 bytes total capacity
@9.53s  	modules: adc,bit,color_utils,cron,crypto,encoder,file,gpio,gpio_pulse,http,i2c,mdns,mqtt,net,node,ow,pcm,perf,pipe,pwm,pwm2,rfswitch,rotary,rtcfifo,rtcmem,rtctime,sigma_delta,sjson,sntp,spi,struct,tls,tmr,uart,websocket,wifi,wifi_monitor
@9.53s   build 2020-08-23 04:19 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
```

### Test code
Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.
```Lua
=net.ifinfo(0)
=net.ifinfo()
```
### NodeMCU startup banner
see above

### Hardware
ESP8266 LoLin v3, esptool says "Chip is ESP8266EX", using the firmware image from [this build](https://github.com/mk-pmb/nodemcu-firmware-wifigpio-pmb/actions/runs/220373173)

### PR DESCRIPTION
**Pull request by vsky279**
Fixes #3249.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

This seems to be an easy catch. Only 0 or 1 are eligible parameters to `eagle_lwip_getif` and `dhcp` table can be added to the resulting table only when `dhcp` table is created.

### CODE REVIEW

File: app/modules/net.c [hunk 1]
```diff
@@ -983,7 +983,10 @@ field_from_ipaddr(lua_State *L, const char * field_name, ip_addr_t* addr) {
 
 static int net_ifinfo( lua_State* L ) {
   int ifidx = luaL_optint(L, 1, 0);
-
+  if (ifidx!=0x00 && ifidx!=0x01) {
```
Comment (marcelstoer) [inline app/modules/net.c:986]:
```suggestion
  if (ifidx != 0 && ifidx != 1) {
```

This assertion is in line with what the documentation has been stating all along 😉

**Comment by nwf** [comment]
Looks right to me.

**Comment by marcelstoer** [comment]
> that will, I think, leave my name on it 

Hhmm, what makes you think so? Git(Hub) just records the committer separately from the author if you "squash and merge": https://github.com/nodemcu/nodemcu-firmware/commits/dev. Looks all dandy to me.

**Comment by vsky279** [comment]
It's squashed now :-)

**Comment by marcelstoer** [comment]
All my tests passed.
