### PR TITLE
Fix the initialization of the wifi default hostname. 

### LINKED ISSUE #3297: Allow the dhcp client hostname to be configured
### Missing feature
The default DHCP client hostname is set to 'ESP-xxxxxx' where the xxxxxx is the last six digits of the mac in hex. It would 
be nice to be able to configure this.

Ideally it would be possible to configure this from LUA, but the problem is that the DHCP starts before the LUA starts. This could be finessed by using a PCR -- this enhancement could probably be built off the startup option PR once that lands.

### PR DESCRIPTION
**Pull request by pjsg**
Fixes #3297.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- N/A The code changes are reflected in the documentation at `docs/*`.

It turns out that the user_rf_pre_init is not called any more. This change really just moves the call into the user_init. However, I also cleaned up the wifi_set_default_host_name() function so it uses fewer #ifdefs

### CODE REVIEW

File: app/modules/wifi.c [hunk 1]
```diff
@@ -1969,28 +1969,24 @@ void wifi_change_default_host_name(void)
   uint8 opmode_temp=wifi_get_opmode();
   wifi_set_opmode_current(STATION_MODE);
   char temp[33] = {0};//32 chars + NULL
+
+  const char *hostname = "NODE";
+#ifdef WIFI_STA_HOSTNAME
+  if (wifi_sta_checkhostname(WIFI_STA_HOSTNAME, strlen(WIFI_STA_HOSTNAME))) {
```
Comment (HHHartmann) [inline app/modules/wifi.c:1975]: If wifi_sta_checkhostname fails and !defined(WIFI_STA_HOSTNAME_APPEND_MAC)
The name will be just NODE

**Review by HHHartmann — CHANGES_REQUESTED** [review]

File: app/modules/wifi.c (hunk 1 above)
Comment (pjsg) [reply app/modules/wifi.c:1975]: On reflection, I think that the possibly better approach is to handle an invalid hostname in the WIFI_STA_HOSTNAME by ignoring this entirely and reverting to the espressif default. It would simplify the code some more, and I really don't want to have this weird fallback handling.....

Comment (HHHartmann) [reply app/modules/wifi.c:1975]: Agreed. 
Apart from that it would be nice if it would be possible to show the failure of
wifi_sta_checkhostname to the user
Maybe just use a name like  "invalid Hostname" then.  Or mention the possibility of invalid Hostname should be described where it is defined

Comment (pjsg) [reply app/modules/wifi.c]: I've added this

**Comment by pjsg** [comment]
@HHHartmann I think that I have addressed all your requests....

File: app/modules/wifi.c [hunk 2]
```diff
@@ -1969,28 +1969,33 @@ void wifi_change_default_host_name(void)
...
-#elif defined(WIFI_STA_HOSTNAME) && defined(WIFI_STA_HOSTNAME_APPEND_MAC)
-  if(strlen(WIFI_STA_HOSTNAME) <= 26 && wifi_sta_checkhostname(WIFI_STA_HOSTNAME, strlen(WIFI_STA_HOSTNAME))){
-    sprintf(temp, "%s%X%X%X", WIFI_STA_HOSTNAME, (mac)[3], (mac)[4], (mac)[5]);
-  }
-  else{
-    sprintf(temp, "NODE-%X%X%X", (mac)[3], (mac)[4], (mac)[5]);
-  }
+  int len = snprintf(temp, sizeof(temp), "%s-%02X%02X%02X", hostname, (mac)[3], (mac)[4], (mac)[5]);
+#else
+  int len = snprintf(temp, sizeof(temp), "%s", hostname);
```
Comment (HHHartmann) [inline app/modules/wifi.c:1985]: If limiting the length here the wifi_sta_checkhostname below has only limited meaning.

Currently the given hostname is just cut off at 32 chars instead of generating an error.

Comment (pjsg) [reply app/modules/wifi.c:1985]: I think that the current code causes a stack overflow if the name is too long! I think that it is better to report an error rather than have the firmware do something surprising...

The checkhostname function is also used when an explicit call to set the wifi hostname is made. I guess that after doing this, you could switch modes to `off` and then back to `STA` to retrigger the DHCP with the new name. I don't know what else this hostname is used for.

**Review by marcelstoer — APPROVED** [review]
