### PR TITLE
Fixes for `ws2812` and `ws2812_effects`

### LINKED ISSUE #2946: shifting more pixels than available for ws2812.buffer:shift reboots
I found this error while writing tests for this module.
So the effort was worth it right away.
This Bug was introduced a while ago, so if we had had tests then it would not be there.

Expected behavior
buffer:shift with more pixels than selected(available) should throw an error.

Actual behavior
Reboots.

Test code
```Lua
buffer = ws2812.newBuffer(4, 4)
buffer:shift(-10)
```
the last commad reboots the mcu

NodeMCU version
NodeMCU 3.0.0.0
branch: dev
commit: 0b90495

Hardware
standard dev board

### PR DESCRIPTION
**Pull request by HHHartmann**
Fixes #2946 #2921 and more.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

Cleanup code and fix issues in `ws2812` and `ws2812_effects`
Besides the afore mentioned ones I fixed a false bounds check in `ws2812_effects.set_brightness` and `ws2812_effects.set_speed`

Also add some automated tests to show the differences between current and this implementation.
You will need to precompile at least the mispec.lua file to not run out of memory.
If you don't like them I will remove them from the PR.

### CODE REVIEW

File: app/modules/ws2812_effects.c [hunk 1]
```diff
@@ -1005,7 +1001,7 @@ static int ws2812_effects_start(lua_State* L) {
     state->counter_mode_call = 0;
     state->counter_mode_step = 0;
     // set the timer
-    os_timer_setfn(&(state->os_t), ws2812_effects_loop, NULL);
+    os_timer_setfn(&(state->os_t), ws2812_effects_loop, (void*)L);
```
Comment (HHHartmann) [inline app/modules/ws2812_effects.c]: Some more testing revealed that passing the lua_State this way does not work.
Trying to find a clean solution.
Any hints welcome!

**Comment by marcelstoer** [comment]
@TerryE would it be a problem for you if we merged this ahead of your large #2912?
