### PR TITLE
Fix Windows build

### LINKED ISSUE #3082: Windows CI build broken
The Windows CI build is broken: https://travis-ci.org/github/nodemcu/nodemcu-firmware/jobs/680981982

### PR DESCRIPTION
**Pull request by HHHartmann**
Fixes #3082.

- [x] This PR is for the `dev` branch rather than for `master`.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.

Windows stuff is buildable again

### CODE REVIEW

**Comment by HHHartmann** [comment]
See https://travis-ci.org/github/nodemcu/nodemcu-firmware/builds/681172914

**Comment by HHHartmann** [comment]
Also replaced a symbolic link by an include to work on docker under windows.

Turned out that replacing a link by a file and git also honoring it is not that trivial under windows.

https://travis-ci.org/github/nodemcu/nodemcu-firmware/builds/681289523

File: app/lua/lobject.h [hunk 1]
```diff
@@ -380,7 +380,7 @@ typedef union Closure {
 */
 
 #define CommonTable CommonHeader; \
-                    lu_byte flags; lu_byte lsizenode; struct Table *metatable;
+                    lu_byte flags; lu_byte lsizenode; struct Table *metatable
```
Comment (nwf) [inline app/lua/lobject.h:384]: Seems OK but unlikely to be Windows-specific?

Comment (HHHartmann) [reply app/lua/lobject.h:384]: the Microsoft windows compiler seems to be more strict about extra semicolon here.

Comment (TerryE) [reply app/lua/lobject.h:384]: No.  The original is incorrect as this will preprocess to have a double semi-colon inside a struct definition.  The `CommonTable` definition should not have a terminating semi-colon.

**Comment by TerryE** [comment]
@HHHartmann @nwf: Gregor, Nathaniel, can you please add me as a explicit reviewer on any PRs that touch the `app/lua*` folder trees.  Thanks

File: app/lua/lobject.h (hunk 1 above)
Comment (nwf) [reply app/lua/lobject.h:384]: Ah ha!  Thanks for clarification. :)
