### PR TITLE
#2954: adapt LuaOTA to the new firmware api for the timer and some other sma…

### LINKED ISSUE #2954: lua_examples/luaOTA crashes when entering _init.lua
### Expected behavior
I've been trying to use the luaOTA example from lua_examples to do deployment. 
Expected behaviour is thus: Not crashing.
.
### Actual behavior
Code immediately panics when entering _init.lua with
```
Starting Provision Checks

PANIC: unprotected error in call to Lua API (luaOTA/_doTick.lua:1: attempt to index global 'self' (a nil value))
```

### Test code
MCVE is simply uploading the code in luaOTA (minus the server component) to the ESP

### NodeMCU version
master
commit: 310faf7fcc9130a296f7f17021d48c6d717f5fb6

### Hardware

NodeMCU board Ver. 0.1 (?)

### PR DESCRIPTION
**Pull request by adeltc**
Notice : This pull request is based on dev branch as the luaota_improvement branch also based on dev

Fixes #2954

Make sure all boxes are checked (add x inside the brackets) when you submit your contribution, remove this sentence before doing so.

- [X] This PR is for the `dev` branch rather than for `master`.
- [X] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [X] I have thoroughly tested my contribution.
- [X] The code changes are reflected in the documentation at `docs/*`.

luaOTA is behind the current version of the firmware.
there is a couple of issues. For example, the new api implementation of the timer doesn't match the latest update. we can see that the line 35 in the _doTick.lua still provide the timer id as first argument which the new version of the firmware doesn't take it. There is couple of other small issue that I fixed. I have a workable version with some fixes in this commit

### CODE REVIEW

File: lua_examples/luaOTA/luaOTAserver.lua [hunk 1]
```diff
@@ -162,6 +162,10 @@ end
 ----------------------------------------------------------------------
 receive_and_parse = function(esp)
   local line = esp:receive("*l")
+  if (not line) then
+    error( "Empty response from ESP, possible cause : file signature failure, check that the secret on ESP and server match", 0)
```
Comment (HHHartmann) [inline lua_examples/luaOTA/luaOTAserver.lua]: Our travis test build fails with the following messages:

> Checking lua_examples/luaOTA/luaOTAserver.lua     2 warnings
>     lua_examples/luaOTA/luaOTAserver.lua:166:121: line is too long (130 > 120)
>     lua_examples/luaOTA/luaOTAserver.lua:166:129: line contains trailing whitespace

To fix them just push your commits to your branch. They will show up here.

**Comment by HHHartmann** [comment]
This one is good!. Thanks for not giving up.

**Comment by marcelstoer** [comment]
Please check the CI build report at https://travis-ci.org/nodemcu/nodemcu-firmware/jobs/640732850

> Checking lua_examples/luaOTA/luaOTAserver.lua     1 warning
                    lua_examples/luaOTA/luaOTAserver.lua:166:81: line contains trailing whitespace

File: lua_examples/luaOTA/_doTick.lua [hunk 2]
```diff
@@ -1,5 +1,4 @@
--- luacheck: globals self
-if (self.timer) then self.timer:stop() end--SAFETRIM
+--if (self.timer) then self.timer:stop() end--SAFETRIM
```
Comment (nwf) [inline lua_examples/luaOTA/_doTick.lua]: If this isn't useful, please just remove it rather than comment it out.

Other than this little nit, this commit looks good to me.

**Comment by nwf** [comment]
Should we Milestone: next-release this one, too, @marcelstoer ?  @adeltc Would you mind fixing the one nit or mind if I did as part of merging this to `dev`?

**Comment by marcelstoer** [comment]
> Should we Milestone: next-release this one, too, @marcelstoer 

Sorry, missed this one 😞 Thanks for circling back to this issue.

@nwf can I ask you to please please set the milestone, assign (a) label(s), and close any connected issues when you merge? Writing release notes is...unpleasant enough - at least for me - even _with_ these measures in place.

**Comment by nwf** [comment]
Whoop, yes, of course.
